// app/license/page.tsx

export const metadata = {
  title: "License — Hook & Script Studio",
  description:
    "License and usage terms for Hook & Script Studio. Understand how you can use the tool and the content it generates.",
};

export default function LicensePage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-10 space-y-6">
      <header className="space-y-2">
        <p className="kicker">Legal</p>
        <h1 className="font-display text-2xl font-semibold">
          License &amp; Acceptable Use
        </h1>
        <p className="text-sm opacity-75">
          This page explains how you&apos;re allowed to use Hook &amp; Script Studio
          and the content it generates. It&apos;s a friendly overview, not formal
          legal advice. You can update or replace this with your own legal text
          at any time.
        </p>
      </header>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">1. What you&apos;re getting</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          Hook &amp; Script Studio is a subscription-based software-as-a-service
          (SaaS) tool that helps you generate hooks, short-form video scripts,
          B-roll ideas, and calls to action. When you pay for access, you&apos;re
          purchasing a license to use the tool — not ownership of the software
          itself.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">2. Usage of generated content</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          You&apos;re free to use, edit, and publish the content generated by Hook
          &amp; Script Studio for:
        </p>
        <ul className="list-disc pl-5 text-sm opacity-80 space-y-1">
          <li>Personal projects</li>
          <li>Client work and freelance projects</li>
          <li>Business marketing and social media content</li>
          <li>Paid offers, digital products, or services you sell</li>
        </ul>
        <p className="text-sm opacity-80 leading-relaxed">
          You&apos;re responsible for reviewing and editing the content before
          publishing. The tool may occasionally generate ideas or language that
          needs to be adjusted to fit your brand, voice, or industry guidelines.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">3. What&apos;s not allowed</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          To keep things fair and safe for everyone, you agree not to:
        </p>
        <ul className="list-disc pl-5 text-sm opacity-80 space-y-1">
          <li>
            Resell, redistribute, or sublicense direct access to Hook &amp; Script
            Studio as your own tool.
          </li>
          <li>
            Use the tool to generate or promote illegal, hateful, or harmful
            content.
          </li>
          <li>
            Try to reverse engineer, copy, or clone the underlying software or
            infrastructure.
          </li>
          <li>
            Share your account access with large groups or use it as a shared
            “team pool” beyond what your plan allows.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">4. Account &amp; subscription</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          Your license to use Hook &amp; Script Studio is active while your
          subscription or access period is active. If your payment fails or your
          subscription is canceled, your access to the tool may be paused or
          removed, but you can usually keep using the content you&apos;ve already
          created.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">5. Changes to this license</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          This license page may be updated over time as the product evolves.
          When that happens, a note may be added to the changelog or footer to
          indicate that the terms changed. Continued use of the product after
          changes means you agree to the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">6. Questions</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          If you have questions about what&apos;s allowed, you can reach out to
          support and ask for clarification before using the tool in a new way.
        </p>
        <p className="text-sm opacity-80">
          Contact:{" "}
          <a
            href="mailto:aveeno350@gmail.com"
            className="underline hover:no-underline"
          >
            aveeno350@gmail.com
          </a>
        </p>
      </section>

      <p className="text-[11px] opacity-60 pt-4">
        Happy Generating!
      </p>
    </main>
  );
}
