// app/terms/page.tsx

export const metadata = {
  title: "Terms of Use — Hook & Script Studio",
  description:
    "Terms of use for Hook & Script Studio. Understand what you agree to when using the product.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-10 space-y-6">
      <header className="space-y-2">
        <p className="kicker">Legal</p>
        <h1 className="font-display text-2xl font-semibold">
          Terms of Use
        </h1>
        <p className="text-sm opacity-75">
          These Terms explain how Hook &amp; Script Studio may be used. By
          accessing or using the product, you agree to these terms. You can
          update this page anytime if you work with an attorney on a custom
          version.
        </p>
      </header>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">1. Who these terms apply to</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          These Terms apply to anyone who uses Hook &amp; Script Studio,
          whether you are on a free trial, using a paid plan, or accessing the
          product through another account (for example, a team account).
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">2. Your responsibilities</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          When you use Hook &amp; Script Studio, you agree to:
        </p>
        <ul className="list-disc pl-5 text-sm opacity-80 space-y-1">
          <li>Provide accurate information when creating and managing your account.</li>
          <li>Keep your login details private and secure.</li>
          <li>Use the product in a lawful way and follow any applicable regulations.</li>
          <li>Respect the intellectual property of others when using generated content.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">3. No guarantees of results</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          Hook &amp; Script Studio is designed to help you generate ideas,
          hooks, scripts, and content faster. However, it does not guarantee
          specific business outcomes such as views, sales, engagement, or
          revenue. You are responsible for how you choose to use the ideas and
          content generated by the tool.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">4. Acceptable use</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          You agree not to use Hook &amp; Script Studio to create or promote:
        </p>
        <ul className="list-disc pl-5 text-sm opacity-80 space-y-1">
          <li>Illegal content or activity.</li>
          <li>Harassment, hate, or targeted abuse toward individuals or groups.</li>
          <li>Misleading scams, phishing attempts, or fraudulent schemes.</li>
          <li>Content that violates platform policies on sites where you publish.</li>
        </ul>
        <p className="text-sm opacity-80 leading-relaxed">
          If the product is used in ways that break these guidelines, access
          may be limited or revoked at any time.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">5. Changes, downtime &amp; updates</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          The product may change over time. Features may be added, updated, or
          removed. There may be occasional downtime for maintenance or due to
          third-party providers (like payment processors or AI APIs). While
          best efforts are made to keep the product stable, no uptime guarantee
          is provided.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">6. Limitation of liability</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          To the fullest extent allowed by law, Hook &amp; Script Studio is
          provided “as is” without warranties of any kind, and any liability
          for indirect, incidental, or consequential damages related to the use
          of the product is limited or excluded. You should review this section
          with a legal professional if you need stricter language for your
          situation.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-base">7. Contact</h2>
        <p className="text-sm opacity-80 leading-relaxed">
          If you have questions about these Terms, you can reach out and ask
          before continuing to use the product.
        </p>
        <p className="text-sm opacity-80">
          Contact:{" "}
          <a
            href="mailto:aveeno350@gmail.com"
            className="underline hover:no-underline"
          >
            aveeno350@gmail.com
          </a>
        </p>
      </section>

    </main>
  );
}

